// ============================================
// PassFast - Mock Data (가상 데이터)
// ============================================

// 자격증 카탈로그
const CATALOG = [
  {
    id: 'info-process',
    name: '정보처리기사',
    category: 'IT',
    icon: 'monitor',
    description: '소프트웨어 개발 및 정보시스템 구축 전문 자격',
    passingScore: 60,
    totalQuestions: 100,
    examTime: 150,
  },
  {
    id: 'sqld',
    name: 'SQLD',
    category: 'IT/DB',
    icon: 'database',
    description: 'SQL 개발자 자격 - 데이터베이스 설계 및 활용',
    passingScore: 60,
    totalQuestions: 50,
    examTime: 90,
  },
  {
    id: 'adsp',
    name: 'ADsP',
    category: '데이터',
    icon: 'bar-chart-2',
    description: '데이터분석 준전문가 - 통계 및 분석 기초',
    passingScore: 60,
    totalQuestions: 50,
    examTime: 90,
  },
  {
    id: 'linux-master',
    name: '리눅스마스터 2급',
    category: 'IT/인프라',
    icon: 'terminal',
    description: '리눅스 운영체제 관리 및 활용 능력 검증',
    passingScore: 60,
    totalQuestions: 80,
    examTime: 100,
  },
  {
    id: 'network-admin',
    name: '네트워크관리사 2급',
    category: 'IT/네트워크',
    icon: 'wifi',
    description: '네트워크 설계·구축·운용 능력 자격',
    passingScore: 60,
    totalQuestions: 60,
    examTime: 90,
  },
];

// 시험 문제 데이터 (자격증 ID별로 분류)
const QUESTIONS = {
  'info-process': [
    {
      id: 1,
      question: '소프트웨어 개발 생명주기(SDLC) 모델 중, 요구사항이 명확할 때 단계별로 순차적으로 진행하는 모델은?',
      choices: ['폭포수 모델', '나선형 모델', '애자일 모델', '프로토타입 모델'],
      answer: 0,
      explanation: '폭포수(Waterfall) 모델은 요구사항이 명확할 때 각 단계를 순차적으로 완료한 후 다음 단계로 넘어가는 전통적인 개발 방법론입니다.',
    },
    {
      id: 2,
      question: '다음 중 객체지향 설계 원칙(SOLID)에서 "개방-폐쇄 원칙(OCP)"의 올바른 설명은?',
      choices: [
        '클래스는 하나의 책임만 가져야 한다',
        '확장에는 열려 있고 변경에는 닫혀 있어야 한다',
        '상위 모듈이 하위 모듈에 의존하면 안 된다',
        '인터페이스를 클라이언트별로 분리해야 한다',
      ],
      answer: 1,
      explanation: 'OCP(Open-Closed Principle)는 기존 코드를 변경하지 않으면서(Closed) 기능을 확장할 수 있어야(Open) 한다는 원칙입니다.',
    },
    {
      id: 3,
      question: 'TCP/IP 프로토콜에서 3-Way Handshake의 올바른 순서는?',
      choices: [
        'SYN → ACK → SYN+ACK',
        'SYN → SYN+ACK → ACK',
        'ACK → SYN → SYN+ACK',
        'SYN+ACK → SYN → ACK',
      ],
      answer: 1,
      explanation: 'TCP 3-Way Handshake는 클라이언트가 SYN을 보내고, 서버가 SYN+ACK로 응답하며, 클라이언트가 ACK를 보내 연결을 확립합니다.',
    },
    {
      id: 4,
      question: '데이터베이스 정규화에서 제3정규형(3NF)의 조건으로 올바른 것은?',
      choices: [
        '모든 속성이 원자값을 가져야 한다',
        '부분 함수 종속을 제거해야 한다',
        '이행적 함수 종속을 제거해야 한다',
        '다치 종속을 제거해야 한다',
      ],
      answer: 2,
      explanation: '제3정규형(3NF)은 제2정규형을 만족하면서 이행적 함수 종속(A→B→C에서 A→C)을 제거한 형태입니다.',
    },
    {
      id: 5,
      question: '다음 중 블랙박스 테스트 기법에 해당하지 않는 것은?',
      choices: ['경계값 분석', '동치 분할', '조건/결정 커버리지', '상태 전이 테스트'],
      answer: 2,
      explanation: '조건/결정 커버리지는 화이트박스 테스트 기법입니다. 블랙박스 테스트는 내부 구조를 보지 않고 입출력만으로 테스트하는 기법입니다.',
    },
  ],
  'sqld': [
    {
      id: 1,
      question: 'SQL에서 NULL 값을 비교할 때 사용해야 하는 연산자는?',
      choices: ['= NULL', 'IS NULL', '== NULL', 'EQUALS NULL'],
      answer: 1,
      explanation: 'SQL에서 NULL은 일반 비교 연산자(=)로 비교할 수 없으며, IS NULL 또는 IS NOT NULL을 사용해야 합니다.',
    },
    {
      id: 2,
      question: '다음 중 DDL(Data Definition Language)에 해당하지 않는 것은?',
      choices: ['CREATE', 'ALTER', 'INSERT', 'DROP'],
      answer: 2,
      explanation: 'INSERT는 DML(Data Manipulation Language)에 해당합니다. DDL에는 CREATE, ALTER, DROP, TRUNCATE 등이 포함됩니다.',
    },
    {
      id: 3,
      question: 'JOIN 시 양쪽 테이블에 모두 존재하는 행만 반환하는 JOIN 유형은?',
      choices: ['LEFT OUTER JOIN', 'RIGHT OUTER JOIN', 'INNER JOIN', 'FULL OUTER JOIN'],
      answer: 2,
      explanation: 'INNER JOIN은 두 테이블에서 조인 조건을 만족하는(양쪽 모두 존재하는) 행만 결과로 반환합니다.',
    },
    {
      id: 4,
      question: 'GROUP BY 절에 대한 설명으로 올바르지 않은 것은?',
      choices: [
        'SELECT 절에 집계함수와 함께 사용된다',
        'WHERE 절 이후에 위치한다',
        'HAVING 절로 그룹 조건을 지정할 수 있다',
        'GROUP BY에 없는 컬럼을 SELECT에 단독으로 사용할 수 있다',
      ],
      answer: 3,
      explanation: 'GROUP BY에 명시되지 않은 컬럼은 SELECT 절에서 집계함수 없이 단독으로 사용할 수 없습니다.',
    },
    {
      id: 5,
      question: '인덱스(Index)에 대한 설명으로 올바르지 않은 것은?',
      choices: [
        '조회 성능을 향상시킨다',
        'INSERT/UPDATE/DELETE 성능이 저하될 수 있다',
        '항상 테이블 풀 스캔보다 빠르다',
        'B-Tree 구조가 일반적으로 사용된다',
      ],
      answer: 2,
      explanation: '소량의 데이터나 대부분의 행을 조회하는 경우 인덱스보다 풀 스캔이 더 효율적일 수 있습니다.',
    },
  ],
  'adsp': [
    {
      id: 1,
      question: '다음 중 데이터 분석 방법론의 단계가 올바르게 나열된 것은?',
      choices: [
        '분석 기획 → 데이터 준비 → 데이터 분석 → 시스템 구현 → 평가 및 전개',
        '데이터 준비 → 분석 기획 → 시스템 구현 → 데이터 분석 → 평가',
        '시스템 구현 → 분석 기획 → 데이터 준비 → 데이터 분석 → 평가',
        '데이터 분석 → 분석 기획 → 데이터 준비 → 평가 → 시스템 구현',
      ],
      answer: 0,
      explanation: '데이터 분석 방법론은 분석 기획 → 데이터 준비 → 데이터 분석 → 시스템 구현 → 평가 및 전개의 순서로 진행됩니다.',
    },
    {
      id: 2,
      question: '다음 중 정형 데이터에 해당하는 것은?',
      choices: ['이메일 본문', 'RDB 테이블', 'SNS 게시글', '동영상 파일'],
      answer: 1,
      explanation: 'RDB(관계형 데이터베이스) 테이블은 고정된 스키마를 갖는 대표적인 정형 데이터입니다.',
    },
    {
      id: 3,
      question: '평균이 0, 표준편차가 1인 분포로 변환하는 정규화 기법은?',
      choices: ['Min-Max 정규화', 'Z-Score 표준화', '로그 변환', '소수 스케일링'],
      answer: 1,
      explanation: 'Z-Score 표준화는 (값-평균)/표준편차로 계산하여 평균 0, 표준편차 1의 분포로 변환합니다.',
    },
    {
      id: 4,
      question: '과적합(Overfitting)을 방지하기 위한 방법이 아닌 것은?',
      choices: ['정규화(Regularization)', '교차 검증(Cross Validation)', '학습 데이터 증가', '모델 복잡도 증가'],
      answer: 3,
      explanation: '모델 복잡도를 증가시키면 학습 데이터에 과적합될 가능성이 높아집니다. 과적합 방지를 위해서는 모델 복잡도를 줄여야 합니다.',
    },
    {
      id: 5,
      question: '상관분석에서 피어슨 상관계수의 범위는?',
      choices: ['0 ~ 1', '-1 ~ 0', '-1 ~ 1', '0 ~ 100'],
      answer: 2,
      explanation: '피어슨 상관계수는 -1에서 1 사이의 값을 가지며, -1은 완전한 음의 상관, 1은 완전한 양의 상관, 0은 상관 없음을 의미합니다.',
    },
  ],
  'linux-master': [
    {
      id: 1,
      question: '리눅스에서 파일의 권한을 변경하는 명령어는?',
      choices: ['chown', 'chmod', 'chgrp', 'umask'],
      answer: 1,
      explanation: 'chmod(change mode)는 파일이나 디렉터리의 접근 권한(읽기/쓰기/실행)을 변경하는 명령어입니다.',
    },
    {
      id: 2,
      question: '리눅스 파일 시스템에서 "/" 디렉터리의 의미는?',
      choices: ['사용자 홈 디렉터리', '루트 디렉터리', '임시 디렉터리', '시스템 설정 디렉터리'],
      answer: 1,
      explanation: '"/"는 리눅스 파일 시스템의 최상위 루트 디렉터리로, 모든 파일과 디렉터리의 시작점입니다.',
    },
    {
      id: 3,
      question: '현재 실행 중인 프로세스 목록을 확인하는 명령어는?',
      choices: ['ls', 'ps', 'df', 'du'],
      answer: 1,
      explanation: 'ps(process status) 명령어는 현재 실행 중인 프로세스의 상태를 보여줍니다.',
    },
    {
      id: 4,
      question: '리눅스에서 파일 내용을 검색하는 명령어는?',
      choices: ['find', 'grep', 'locate', 'which'],
      answer: 1,
      explanation: 'grep은 파일 내용에서 특정 패턴(문자열)을 검색하는 명령어입니다. find는 파일명으로 검색합니다.',
    },
    {
      id: 5,
      question: 'vi 에디터에서 저장하지 않고 강제 종료하는 명령은?',
      choices: [':wq', ':q!', ':x', ':w'],
      answer: 1,
      explanation: ':q!는 변경사항을 저장하지 않고 강제로 vi 에디터를 종료하는 명령입니다.',
    },
  ],
  'network-admin': [
    {
      id: 1,
      question: 'OSI 7계층에서 데이터 링크 계층의 전송 단위는?',
      choices: ['비트(Bit)', '프레임(Frame)', '패킷(Packet)', '세그먼트(Segment)'],
      answer: 1,
      explanation: '데이터 링크 계층(2계층)의 전송 단위는 프레임(Frame)입니다. 물리계층은 비트, 네트워크계층은 패킷, 전송계층은 세그먼트입니다.',
    },
    {
      id: 2,
      question: '서브넷 마스크 255.255.255.0일 때 사용 가능한 호스트 수는?',
      choices: ['256개', '254개', '255개', '128개'],
      answer: 1,
      explanation: '네트워크 주소와 브로드캐스트 주소를 제외하면 256-2=254개의 호스트 주소를 사용할 수 있습니다.',
    },
    {
      id: 3,
      question: 'HTTP의 기본 포트 번호는?',
      choices: ['21', '22', '80', '443'],
      answer: 2,
      explanation: 'HTTP는 포트 80번을 기본으로 사용합니다. 443은 HTTPS, 22는 SSH, 21은 FTP의 기본 포트입니다.',
    },
    {
      id: 4,
      question: 'IP 주소를 MAC 주소로 변환하는 프로토콜은?',
      choices: ['RARP', 'ARP', 'ICMP', 'IGMP'],
      answer: 1,
      explanation: 'ARP(Address Resolution Protocol)는 IP 주소를 물리적 MAC 주소로 변환하는 프로토콜입니다.',
    },
    {
      id: 5,
      question: 'VLAN에 대한 설명으로 올바르지 않은 것은?',
      choices: [
        '물리적 위치와 관계없이 논리적으로 네트워크를 분리한다',
        '브로드캐스트 도메인을 분리할 수 있다',
        '보안성을 높일 수 있다',
        'VLAN 간 통신에 라우터가 필요하지 않다',
      ],
      answer: 3,
      explanation: '서로 다른 VLAN 간 통신을 위해서는 라우터(또는 L3 스위치)가 필요합니다. VLAN은 논리적으로 분리된 네트워크이기 때문입니다.',
    },
  ],
};
